name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main        # For production deployment
      - development # For development deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set environment for deployment
        run: |
          if [[ $GITHUB_REF == 'refs/heads/development' ]]; then
            cp .env.development .env # Use the .env.development file for the development branch
          else
            cp .env.production .env # Use the .env.production file for the main branch
          fi

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'

          # If it's the 'development' branch, deploy to /development subfolder
          if: github.ref == 'refs/heads/development'
          destination: 'gh-pages/development'

          # For 'main' branch, deploy to the root of gh-pages
          if: github.ref == 'refs/heads/main'
          publish_branch: gh-pages
